DROP PROCEDURE [dbo].[COMPANY_g]
GO
CREATE PROCEDURE [dbo].[COMPANY_g]
(
 @pXMLFILE XML 
)
AS
    BEGIN 
	 
      DECLARE @pCOMPID INT ,  
	  @pCOMPCODE nvarchar(20), 
	  @pCOMPNAME nvarchar(120), 
	  @pDESC NVARCHAR(120) ,
	  @pUSERID INT    
     ------------------------------------------------------------------------------------------
	 DECLARE @verrorId INT 
     DECLARE @vspName VARCHAR(100) 
     SET @vspName = 'COMPANY_g'
     
     SELECT @pCOMPID = N.C.value('@COMPID[1]', 'INT'),
			@pCOMPCODE = N.C.value('@COMPCODE[1]', 'nvarchar(20)'),
			@pCOMPNAME = N.C.value('@COMPNAME[1]', 'nvarchar(120)'), 
			@pDESC = N.C.value('@DESC[1]', 'NVARCHAR(120)'),
			@pUSERID = N.C.value('@USERID[1]', 'INT') 
     FROM   @pXMLFILE.nodes('//XMLFILE/SPXML/SPDETAILS') N ( C )
    
     EXEC DBLOG_c @pXMLFILE = @pXMLFILE, @pSPNAME = @vSPNAME
     ------------------------------------------------------------------------------------------
        
		BEGIN TRY 
			
			SELECT  
			ISNULL(C.COMPID,0)AS COMPID,
			ISNULL(C.COMPCODE,'')AS COMPCODE,
			ISNULL(C.COMPNAME,'')AS COMPNAME,
			ISNULL(C.ADDR1COMPLEXNAME,'')AS ADDR1COMPLEXNAME,
			ISNULL(C.ADDR1STREETNO,'')AS ADDR1STREETNO,
			ISNULL(C.ADDR1STREETNAME,'')AS ADDR1STREETNAME,
			ISNULL(C.ADDR1POSTALCODE,'')AS ADDR1POSTALCODE, 
			ISNULL(C.ADDR1COUNTRYNAME,'') AS ADDR1COUNTRYNAME,  
			ISNULL(C.ADDR1STATENAME,'') AS ADDR1STATENAME, 
			ISNULL(C.ADDR1CITYNAME,'') AS ADDR1CITYNAME,
			ISNULL(C.ADDR2SAMEASADDR1,'')AS ADDR2SAMEASADDR1,
			ISNULL(C.ADDR2COMPLEXNAME,'')AS ADDR2COMPLEXNAME,
			ISNULL(C.ADDR2STREETNO,'')AS ADDR2STREETNO,
			ISNULL(C.ADDR2STREETNAME,'')AS ADDR2STREETNAME,
			ISNULL(C.ADDR2POSTALCODE,'')AS ADDR2POSTALCODE, 
			ISNULL(C.ADDR2COUNTRYNAME,'') AS ADDR2COUNTRYNAME,   
			ISNULL(C.ADDR2STATENAME,'') AS ADDR2STATENAME, 
			ISNULL(C.ADDR2CITYNAME,'') AS ADDR2CITYNAME,
			ISNULL(C.PRIMARYPHONE,'')AS PRIMARYPHONE,
			ISNULL(C.SECONDARYPHONE,'')AS SECONDARYPHONE,
			ISNULL(C.FAX,'')AS FAX,
			ISNULL(C.EMAILID,'')AS EMAILID,
			ISNULL(C.WEBSITE,'')AS WEBSITE,
			C.ESTABLISHEDIN,
			ISNULL(C.MANPOWERWORKING,0)AS MANPOWERWORKING, 
			ISNULL(C.REGNO,'')AS REGNO,
			C.CREATEDON,
			C.CREATEDBY,
			C.UPDATEDON,
			C.UPDATEDBY,
			C.ISACTIVE,
			F.PROCESSMONTHLY,
			F.MONTHSINTAXYEAR,
			F.FIRSTMONTHENDDATE,
			F.STARTINGMONTH
			FROM  dbo.COMPANY C 
			INNER JOIN FREQUENCYPERIOD F ON F.COMPID=C.COMPID
			WHERE
			1 = CASE WHEN @pUSERID=0 THEN 1 WHEN @pUSERID<>0 AND C.CREATEDBY=@pUSERID THEN 1 ELSE 0 END
			AND 1 = CASE WHEN @pCOMPID=0 THEN 1 WHEN @pCOMPID<>0 AND C.COMPID= @pCOMPID THEN 1 ELSE 0 END 
			AND 1 = CASE WHEN LEN(@pCOMPCODE)=0 THEN 1 WHEN LEN(@pCOMPCODE)<>0 AND C.COMPCODE LIKE '%'+ @pCOMPCODE +'%' THEN 1 ELSE 0 END
			AND 1 = CASE WHEN LEN(@pCOMPNAME)=0 THEN 1 WHEN LEN(@pCOMPNAME)<>0 AND C.COMPNAME LIKE '%'+ @pCOMPNAME +'%' THEN 1 ELSE 0 END 

		END TRY 
   
		BEGIN CATCH

		SET @vERRORID = 0 - ERROR_NUMBER() 
		
		SELECT  0 - ERROR_NUMBER() AS 'ID' 

		EXECUTE LogError_i @pXMLFILE, @vERRORID OUTPUT; 

		END CATCH; 
    END 
GO
