IF (OBJECT_ID('COMPANY_g') IS NOT NULL) 
BEGIN 
DROP PROCEDURE COMPANY_g
END
GO
CREATE PROCEDURE [dbo].[COMPANY_g]
(
 @pXMLFILE XML 
)
AS
    BEGIN 
	 
      DECLARE @pCOMPID INT ,  
	  @pCOMPCODE nvarchar(20), 
	  @pCOMPNAME nvarchar(120), 
	  @pDESC NVARCHAR(120)    
     ------------------------------------------------------------------------------------------
	 DECLARE @verrorId INT 
     DECLARE @vspName VARCHAR(100) 
     SET @vspName = 'COMPANY_g'
     
     SELECT @pCOMPID = N.C.value('@COMPID[1]', 'INT'),
			@pCOMPCODE = N.C.value('@COMPCODE[1]', 'nvarchar(20)'),
			@pCOMPNAME = N.C.value('@COMPNAME[1]', 'nvarchar(120)'), 
			@pDESC = N.C.value('@DESC[1]', 'NVARCHAR(120)') 
     FROM   @pXMLFILE.nodes('//XMLFILE/SPXML/SPDETAILS') N ( C )
    
     EXEC DBLOG_c @pXMLFILE = @pXMLFILE, @pSPNAME = @vSPNAME
     ------------------------------------------------------------------------------------------
        
		BEGIN TRY 
			
			SELECT  
			C.COMPCODE,
			C.COMPNAME,
			C.ADDR1COMPLEXNAME,
			C.ADDR1STREETNO,
			C.ADDR1STREETNAME,
			C.ADDR1POSTALCODE,
			C.ADDR1COUNTRYID,
			CM.COUNTRYNAME AS ADDR1COUNTRYNAME,
			CM.COUNTRYCODE AS ADDR1COUNTRYCODE,
			C.ADDR1STATEID,
			S.STATECODE AS ADDR1STATECODE,
			S.STATENAME AS ADDR1STATENAME,
			C.ADDR1CITYID, 
			CIM.CITYCODE AS ADDR1CITYCODE,
			CIM.CITYNAME AS ADDR1CITYNAME,
			C.ADDR2SAMEASADDR1,
			C.ADDR2COMPLEXNAME,
			C.ADDR2STREETNO,
			C.ADDR2STREETNAME,
			C.ADDR2POSTALCODE,
			C.ADDR2COUNTRYID,
			CM1.COUNTRYNAME AS ADDR2COUNTRYNAME,
			CM1.COUNTRYCODE AS ADDR2COUNTRYCODE,
			C.ADDR2STATEID,
			S1.STATECODE AS ADDR2STATECODE,
			S1.STATENAME AS ADDR2STATENAME,
			C.ADDR2CITYID,
			CIM1.CITYCODE AS ADDR2CITYCODE,
			CIM1.CITYNAME AS ADDR2CITYNAME,
			C.PRIMARYPHONE,
			C.SECONDARYPHONE,
			C.FAX,
			C.EMAILID,
			C.WEBSITE,
			C.ESTABLISHEDIN,
			C.MANPOWERWORKING, 
			C.REGNO,
			C.CREATEDON,
			C.CREATEDBY,
			C.UPDATEDON,
			C.UPDATEDBY 
			FROM  dbo.COMPANY C
			LEFT JOIN dbo.STATEMAST S ON S.STATEID=C.ADDR1STATEID
			LEFT JOIN dbo.COUNTRYMAST CM ON CM.COUNTRYID=C.ADDR1COUNTRYID 
			LEFT JOIN dbo.CITYMAST CIM ON CIM.CITYID=C.ADDR1CITYID 
			LEFT JOIN dbo.STATEMAST S1 ON S1.STATEID=C.ADDR2STATEID
			LEFT JOIN dbo.COUNTRYMAST CM1 ON CM1.COUNTRYID=C.ADDR2COUNTRYID
			LEFT JOIN dbo.CITYMAST CIM1 ON CIM.CITYID=C.ADDR2CITYID 
			WHERE
			1 = CASE WHEN  @pCOMPID>0 AND COMPID= @pCOMPID THEN 1 ELSE 0 END  

		END TRY 
   
		BEGIN CATCH

		SET @vERRORID = 0 - ERROR_NUMBER() 
		
		SELECT  0 - ERROR_NUMBER() AS 'ID' 

		EXECUTE LogError_i @pXMLFILE, @vERRORID OUTPUT; 

		END CATCH; 
    END 
GO
