IF (OBJECT_ID('EMPLOYEE_g') IS NOT NULL) 
BEGIN 
DROP PROCEDURE EMPLOYEE_g
END
GO
CREATE PROCEDURE [dbo].[EMPLOYEE_g]
(
 @pXMLFILE XML 
)
AS
    BEGIN 
	 
      DECLARE @pEMPID INT   
	  DECLARE @pDESC VARCHAR(50)   
	  DECLARE @pUSERID NVARCHAR(MAX)
     ------------------------------------------------------------------------------------------
	 DECLARE @verrorId INT 
     DECLARE @vspName VARCHAR(100) 
     SET @vspName = 'EMPLOYEE_g'
     
     SELECT @pEMPID = N.C.value('@EMPID[1]', 'INT'),
			@pDESC = N.C.value('@DESC[1]', 'VARCHAR(50)'),
			@pUSERID = N.C.value('@USERID[1]', 'INT') 
     FROM   @pXMLFILE.nodes('//XMLFILE/SPXML/SPDETAILS') N ( C )
    
     EXEC DBLOG_c @pXMLFILE = @pXMLFILE, @pSPNAME = @vSPNAME
     ------------------------------------------------------------------------------------------
        
		BEGIN TRY 
			
			SELECT 
				EMPID,
				ISNULL(EMPCODE,'') AS EMPCODE,
				ISNULL(TITLE,'') AS TITLE,
				ISNULL(FIRSTNAME,'') AS FIRSTNAME,
				ISNULL(MIDDLENAME,'') AS MIDDLENAME,
				ISNULL(LASTNAME,'') AS LASTNAME,
				ISNULL(NICKNAME,'') AS NICKNAME,
				REPLACE(CONVERT(VARCHAR(11),ISNULL(STARTDATE,''), 106),' ','-')AS STARTDATE, 
				REPLACE(CONVERT(VARCHAR(11),ISNULL(DOB,''), 106),' ','-')AS DOB,   
				ISNULL(NATIONALID,'') AS NATIONALID, 
				ISNULL(PASSPORTNO,'') AS PASSPORTNO,
				ISNULL(COUNTRYOFISSUE,'') AS COUNTRYOFISSUE,
				ISNULL(GENDER,'') AS GENDER,
				ISNULL(MARITALSTATUS,'') AS MARITALSTATUS,
				ISNULL(DEPENDENT,'') AS DEPENDENT,
				ISNULL(YEARSOFSERVICE,'') AS YEARSOFSERVICE,
				ISNULL(ADDR1COMPLEXNAME,'') AS ADDR1COMPLEXNAME,
				ISNULL(ADDR1STREETNO,'') AS ADDR1STREETNO,
				ISNULL(ADDR1STREETNAME,'') AS ADDR1STREETNAME,
				ISNULL(ADDR1POSTALCODE,'') AS ADDR1POSTALCODE,
				ISNULL(ADDR1COUNTRYNAME,'') AS ADDR1COUNTRYNAME,
				ISNULL(ADDR1STATENAME,'') AS ADDR1STATENAME,
				ISNULL(ADDR1CITYNAME,'') AS ADDR1CITYNAME, 
				ISNULL(ADDR2SAMEASADDR1,'') AS ADDR2SAMEASADDR1,
				ISNULL(ADDR2COMPLEXNAME,'') AS ADDR2COMPLEXNAME,
				ISNULL(ADDR2STREETNO,'') AS ADDR2STREETNO,
				ISNULL(ADDR2STREETNAME,'') AS ADDR2STREETNAME,
				ISNULL(ADDR2POSTALCODE,'') AS ADDR2POSTALCODE,
				ISNULL(ADDR2COUNTRYNAME,'') AS ADDR2COUNTRYNAME,
				ISNULL(ADDR2STATENAME,'') AS ADDR2STATENAME,
				ISNULL(ADDR2CITYNAME,'') AS ADDR2CITYNAME, 
				ISNULL(WORKPHONE,'') AS WORKPHONE,
				ISNULL(HOMEPHONE,'') AS HOMEPHONE,
				ISNULL(CELLNO,'') AS CELLNO,
				ISNULL(FAXNO,'') AS FAXNO,
				ISNULL(SPOUSENAME,'') AS SPOUSENAME,
				ISNULL(SPOUSENO,'') AS SPOUSENO,
				ISNULL(EMAILID,'') AS EMAILID,
				DAILYRATE,
				WEEKLYRATE,
				MONTHLYRATE,
				HOURLYRATE,
				PREVIUSYEARLYPAY,
				REPLACE(CONVERT(VARCHAR(11),ISNULL(LASTINCREAMENTDATE,''), 106),' ','-')AS LASTINCREAMENTDATE,
				REPLACE(CONVERT(VARCHAR(11),ISNULL(TERMINATIONDATE,''), 106),' ','-')AS TERMINATIONDATE,    
				AVGHOURPERDAY,
				HOURPERWEEK,
				DAYSPERMONTH,
				ISNULL(WEEKDAYS,'') AS WEEKDAYS,
				ANNUALSTANDARDLEAVE,
				ANNUALSICKLEAVE,
				ANNUALOPTIONALLEAVE,
				ISACTIVE,
				COMPID, 
				REPLACE(CONVERT(VARCHAR(11),ISNULL(CREATEDON,''), 106),' ','-')AS CREATEDON,
				CREATEDBY,
				REPLACE(CONVERT(VARCHAR(11),ISNULL(UPDATEDON,''), 106),' ','-')AS UPDATEDON, 
				UPDATEDBY
			FROM  dbo.EMPLOYEE
			WHERE
			1 = CASE WHEN  @pEMPID=0 THEN 1 WHEN @pEMPID<>0 AND EMPID=@pEMPID THEN 1 ELSE 0 END 
			AND 1 = CASE WHEN  LEN(@pDESC)=0 THEN 1 WHEN LEN(@pDESC) <> 0 AND EMPCODE LIKE '%'+@pDESC+'%' THEN 1 ELSE 0 END 
			AND ISACTIVE=1

		END TRY 
   
		BEGIN CATCH

		SET @vERRORID = 0 - ERROR_NUMBER() 
		
		SELECT  0 - ERROR_NUMBER() AS 'ID' 

		EXECUTE LogError_i @pXMLFILE, @vERRORID OUTPUT; 

		END CATCH; 
    END 
GO
