CREATE TABLE [dbo].[CITYMAST]
(
[CITYID] [int] NOT NULL IDENTITY(1, 1),
[CITYCODE] [nvarchar] (20) NULL,
[CITYNAME] [nvarchar] (120) NOT NULL,
[COUNTRYID] [int] NOT NULL,
[STATEID] [int] NOT NULL,
[ISACTIVE] [bit] NULL DEFAULT ((1)),
[LATITUDE] [varchar] (20) NULL,
[LONGITUDE] [varchar] (20) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CITYMAST] ADD CONSTRAINT [PK_CITYMAST] PRIMARY KEY CLUSTERED  ([CITYID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CITYMAST] ADD CONSTRAINT [UK_CITYMAST_CITYNAME] UNIQUE NONCLUSTERED  ([CITYNAME], [STATEID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CITYMAST] ADD CONSTRAINT [UK_CITYMAST_CITYCODE] UNIQUE NONCLUSTERED  ([CITYCODE], [COUNTRYID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CITYMAST] ADD CONSTRAINT [FK_CITYMAST_C] FOREIGN KEY ([COUNTRYID]) REFERENCES [dbo].[COUNTRYMAST] ([COUNTRYID])
GO
ALTER TABLE [dbo].[CITYMAST] ADD CONSTRAINT [FK_CITYMAST_S] FOREIGN KEY ([STATEID]) REFERENCES [dbo].[STATEMAST] ([STATEID])
GO
