DROP TABLE [dbo].[COMPANY]
GO
CREATE TABLE [dbo].[COMPANY]
(
[COMPID] [int] NOT NULL IDENTITY(1, 1),
[COMPCODE] [nvarchar] (20)  NOT NULL,
[COMPNAME] [nvarchar] (120) NOT NULL,
[ADDR1COMPLEXNAME] [nvarchar] (500) NULL,
[ADDR1STREETNO] [nvarchar] (500) NULL,
[ADDR1STREETNAME] [nvarchar] (500) NULL,
[ADDR1POSTALCODE] [nvarchar] (255)  NULL,
[ADDR1COUNTRYID] [int] NOT NULL,
[ADDR1STATEID] [int] NOT NULL,
[ADDR1CITYID] [int] NOT NULL, 
[ADDR2SAMEASADDR1] [bit] NULL,
[ADDR2COMPLEXNAME] [nvarchar] (500) NULL,
[ADDR2STREETNO] [nvarchar] (500) NULL,
[ADDR2STREETNAME] [nvarchar] (500) NULL,
[ADDR2POSTALCODE] [nvarchar] (255)  NULL,
[ADDR2COUNTRYID] [int] NOT NULL,
[ADDR2STATEID] [int] NOT NULL,
[ADDR2CITYID] [int] NOT NULL,
[PRIMARYPHONE] [nvarchar] (20) NULL,
[SECONDARYPHONE] [nvarchar] (20) NULL,
[FAX] [nvarchar] (20) NULL,
[EMAILID] [nvarchar] (120) NULL,
[WEBSITE] [nvarchar] (500) NULL,
[ESTABLISHEDIN] [date] NULL,
[MANPOWERWORKING] [int] NULL, 
[REGNO] [nvarchar] (30) NULL,
[ISACTIVE] [bit] NULL DEFAULT ((1)),
[CREATEDON] [datetime]  NULL ,
[CREATEDBY] [int]  NULL ,
[UPDATEDON] [datetime]  NULL , 
[UPDATEDBY] [int]  NULL 

) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COMPANY] ADD CONSTRAINT [PK_COMPANY] PRIMARY KEY CLUSTERED  ([COMPID]) ON [PRIMARY]
 

