DROP TABLE [dbo].[EMPLOYEEPAYMAPPING]
GO
CREATE TABLE [dbo].[EMPLOYEEPAYMAPPING]
(
[MID] [bigint] NOT NULL IDENTITY(1, 1),
[HEADID] [bigint]  NOT NULL,
[EMPID] [bigint]  NOT NULL, 
[CALSEQUENCE] [INT] NOT NULL,
[AMOUNT] [decimal] (21, 6) NOT NULL ,
[IsCalculation] [bit] NULL,
[FORMULA] [VARCHAR] (5000) NOT NULL,
[ISACTIVE] [bit] NULL DEFAULT ((1)),
[CREATEDON] [datetime]  NULL ,
[CREATEDBY] [int]  NULL ,
[UPDATEDON] [datetime]  NULL , 
[UPDATEDBY] [int]  NULL 
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EMPLOYEEPAYMAPPING] ADD CONSTRAINT [PK_EMPLOYEEPAYMAPPING] PRIMARY KEY CLUSTERED  ([MID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EMPLOYEEPAYMAPPING] ADD CONSTRAINT [UK_EMPLOYEEPAYMAPPING] UNIQUE NONCLUSTERED  ([HEADID],[EMPID]) ON [PRIMARY]
GO
 ALTER TABLE [dbo].[EMPLOYEEPAYMAPPING] ADD CONSTRAINT [FK_EMPLOYEEPAYMAPPING] FOREIGN KEY ([HEADID]) REFERENCES [dbo].[PAYSLIPHEADS] ([HEADID])
 Go

