DROP TABLE FORMULAVRIABLE
GO
CREATE TABLE FORMULAVRIABLE
(
	VARID BIGINT NOT NULL IDENTITY(1,1),
	HEADID BIGINT,
	VARIABLE CHAR(2),
	FIELDID BIGINT,
	TESTVALUE DECIMAL(21,6)
)ON [PRIMARY]
GO
ALTER TABLE [dbo].[FORMULAVRIABLE] ADD CONSTRAINT [PK_FORMULAVRIABLE] PRIMARY KEY CLUSTERED  ([VARID]) ON [PRIMARY]

