
DROP TABLE FORMULACALCULATION
GO
CREATE TABLE FORMULACALCULATION
(
	CALID BIGINT NOT NULL IDENTITY(1,1),
	VARID BIGINT,
	HEADID BIGINT,
	CONDITION NVARCHAR(1000),
	CALCULATION NVARCHAR(1000),
	ISEXIT BIT,
	RESULT CHAR(3),
	TESTVALUE DECIMAL(21,6),
	COMPID INT NOT NULL,
	ISACTIVE BIT NULL,
	CREATEDON datetime  NULL ,
	CREATEDBY int  NULL ,
	UPDATEDON datetime  NULL , 
	UPDATEDBY int  NULL 
)
ON [PRIMARY]
GO
ALTER TABLE [dbo].[FORMULACALCULATION] ADD CONSTRAINT [PK_FORMULACALCULATION] PRIMARY KEY CLUSTERED  ([CALID]) ON [PRIMARY]

