DROP TABLE [dbo].[FREQUENCYPERIOD]
GO
CREATE TABLE [dbo].[FREQUENCYPERIOD]
(
[MID] [int] NOT NULL  IDENTITY(1, 1),
[PROCESSMONTHLY] [bit],
[STARTINGMONTH] [int] NOT NULL,
[FIRSTMONTHENDDATE] [date] NOT NULL ,
[MONTHSINTAXYEAR] [int] NOT NULL,
[COMPID] [int] NOT NULL, 
[ISACTIVE] [bit] NULL DEFAULT ((1)),
[ISCLOSED] [bit] NULL DEFAULT((0)),
[CREATEDON] [datetime] NULL,
[CREATEDBY] [int] NULL,
[UPDATEDON] [datetime] NULL,
[UPDATEDBY] [int] NULL 
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FREQUENCYPERIOD] ADD CONSTRAINT [PK_FREQUENCYPERIOD] PRIMARY KEY CLUSTERED  ([MID]) ON [PRIMARY]
GO