DROP TABLE [dbo].[PAYSLIPHEADS]
GO
CREATE TABLE [dbo].[PAYSLIPHEADS]
(
[HEADID] [bigint] NOT NULL IDENTITY(1, 1),
[HEADCODE] [nvarchar] (20)  NOT NULL,
[DESC] [nvarchar] (200) NULL,
[TRANSACTIONTYPE] [int] NOT NULL,
[ISACTIVE] [bit] NULL DEFAULT ((1)),
[COMPID] [INT] NULL,
[CREATEDON] [datetime]  NULL ,
[CREATEDBY] [int]  NULL ,
[UPDATEDON] [datetime]  NULL , 
[UPDATEDBY] [int]  NULL 
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PAYSLIPHEADS] ADD CONSTRAINT [PK_PAYSLIPHEADS] PRIMARY KEY CLUSTERED  ([HEADID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PAYSLIPHEADS] ADD CONSTRAINT [UK_PAYSLIPHEADS] UNIQUE NONCLUSTERED  ([HEADCODE],[COMPID]) ON [PRIMARY]
GO
 ALTER TABLE [dbo].[PAYSLIPHEADS] ADD CONSTRAINT [FK_PAYSLIPHEADS] FOREIGN KEY ([TRANSACTIONTYPE]) REFERENCES [dbo].[StatusMaster] ([STATUSID])
 Go

