DROP TABLE dbo.RATEMASTER
GO
CREATE TABLE dbo.RATEMASTER
(
	[RATEID] [INT] NOT NULL IDENTITY(1,1),
	[RATECODE] [VARCHAR](20) NOT NULL,
	[DESCRIPTION] [VARCHAR](500) NULL,
	[RATE] [DECIMAL](21,6) NULL,
	[ISACTIVE] [bit] NULL DEFAULT ((1)),
	[CREATEDON] [datetime]  NULL ,
	[CREATEDBY] [int]  NULL ,
	[UPDATEDON] [datetime]  NULL , 
	[UPDATEDBY] [int]  NULL 
)ON [PRIMARY]
GO
ALTER TABLE [dbo].[RATEMASTER] ADD CONSTRAINT [PK_RATEMASTER] PRIMARY KEY CLUSTERED  ([RATEID]) ON [PRIMARY]
