CREATE TABLE [dbo].[STATEMAST]
(
[STATEID] [int] NOT NULL IDENTITY(1, 1),
[STATECODE] [nvarchar] (20)  NULL,
[SHORTNAME] [nvarchar] (60)  NULL,
[STATENAME] [nvarchar] (120)  NOT NULL,
[COUNTRYID] [int] NOT NULL,
[ISACTIVE] [bit] NULL CONSTRAINT [DF_STATEMAST_ISACTIVE] DEFAULT ((1)) ,
[CREATEDON] [datetime]  NULL ,
[CREATEDBY] [int]  NULL ,
[UPDATEDON] [datetime]  NULL , 
[UPDATEDBY] [int]  NULL 

) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STATEMAST] ADD CONSTRAINT [PK_STATEMAST] PRIMARY KEY CLUSTERED  ([STATEID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STATEMAST] ADD CONSTRAINT [UK_STATEMAST] UNIQUE NONCLUSTERED  ([STATECODE]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STATEMAST] ADD CONSTRAINT [FK_STATEMAST_C] FOREIGN KEY ([COUNTRYID]) REFERENCES [dbo].[COUNTRYMAST] ([COUNTRYID])
GO
